### ISSUE TITLE
Natural(-555) returns 18446744073709551061

### ISSUE THREAD

**Issue by kevinmeredith** [non/spire#440]
Given the https://github.com/non/spire#number-types's explanation of Natural:

>* Natural unsigned, immutable, arbitrary precision integer

is this a bug?

```
scala> import spire.math.Natural
import spire.math.Natural

scala> Natural(-555)
res1: spire.math.Natural = 18446744073709551061

scala> Natural(BigInt(-555))
java.lang.IllegalArgumentException: negative numbers not allowed: -555
```

On a side note, I'm not sure which `apply` method is getting used. I don't see any methods accepting an `Int` - https://github.com/non/spire/blob/master/core/src/main/scala/spire/math/Natural.scala#L558-L583.

Perhaps the `PositveInt` macro would be useful to apply here per https://github.com/non/spire/issues/437?

**Comment by non** [comment]
Hi Kevin,

First of all, `Int` values will be promoted to `Long` values, so `apply(Long)` is being used.

This is not a bug (except in the sense that it wasn't documented properly). Since Scala (and Java) have no good way to provide literal unsigned numbers, programmers often have to use negative numbers as if they were their unsigned two's complement value.

Here `-555` is being treated as a positive unsigned long value (using its two's complement value).

However, we don't want to do this for all values, only for `Long` values, since the only goal here is to allow programmers to treat a `Long` value as if it were unsigned -- `BigInt` is perfectly capable of representing `18446744073709551061` directly. Furthermore, since `ULong` and `Long` erase to the same type in many cases, we can't easily forbid `Long` without messing up the machinery for `ULong`.

I'm open to a better system, but it's important that we are able to accept any of the `2^64` possible unsigned long values.

**Comment by non** [comment]
I still think we should open a bug about poor documentation for `Natural`. I'll try to remember to do it tonight if you don't get to it first.
