### ISSUE TITLE
Rational API changes

### ISSUE THREAD

**Issue by non** [non/spire#453]
I'd like to try to improve the `Rational` API a bit. Here are some concrete suggestions:

1. Change `.numerator` and `.denominator` to return `SafeLong`.
2. Add `.isZero` method
3. Consider using `SafeLong` instead of `BigInt` for "big" variant.
4. Add conversion methods to `Real` and `Algebraic`
5. Simplify inheritance scheme if possible.
6. Look into moving `.nroot` to somewhere more appropriate.

(1) is pretty straightforward: creating a `BigInt` from a `Long` is more expensive than wrapping a `Long` or `BigInt`).

(2) is just about creating consistency between our concrete types (and supporting more literate programming: `x.isZero` reads better than `x.signum == 0` for something that is quite common).

(3) is potentially contentious and will require a lot of benchmarking. The thought is that operations on `SafeLong` are not much slower than `BigInt`, will automatically convert to `Long` where possible, and will allow *partial* big rationals (i.e. large numerator with `1L` denominator, or vice-versa). The concern is that extra costs will be significant enough to hurt overall performance in "normal" use.

(4) Is pretty safe, and just about consistency.

(5) Right now there is a tangled web of classes that make up the various rational types. It would be nice to move to something much simpler if possible. However, we have to be sure that any change doesn't negatively impact performance.

(6) We have `.sqrt` and `.nroot` methods for `Int`, `Long`, `BigInt`, and `SafeLong` scattered around Spire. These methods are inexact (and maybe should be renamed) but end up being useful in a lot of situations. Let's try to figure out a strategy that makes these available in an intuitive way.

**Comment by non** [comment]
I'd appreciate any input from folks who've used `Rational`, but especially @tixxit and @rklaehn.

**Comment by rklaehn** [comment]
I very much agree with most points.

(1) Good idea. SafeLong is the spire way to represent an arbitrary size integer, so it is natural to use that even disregarding performance considerations.

(2) I agree completely. In fact I have a isZero enhancement method in my package object for packages that heavily use rationals for this purpose. I also have `def isOne: Boolean = underlying.compareToOne == 0` as a performance optimization for comparing to one, but that might be too specific.

(4) I am not sure if conversions to unrelated types should be part of a type, or if they should be added from outside at some point. But for now I agree about adding them.

(5) Also agree. The traits were originally meant to allow code reuse, I guess. But we ended up implementing them differently for LongRational and BigRational anyway for performance reasons. So it should be possible to simplify this.

About (3)

A few thougts:

I am not sure if using SafeLong for numerator and denominator without any additional changes will yield performance improvements.

In the case of a BigRational with numerator and denominator above long magnitude, you will have the BigRational instance containing two SafeLong instances, which wrap two scala.math.BigInt instances, which wrap two java.math.BigInteger, which wrap two Array[Int]. There is a bit too much wrapping going on for my liking.

I think that scala.math.BigInt just exists to enable our old scourge cooperative equality, and because value classes did not exist back when it was written. So why not change SafeLongBigInt to directly wrap java.math.BigInteger? That way we get rid of one wrapper and can use SafeLong for numerator and denominator without any additional wrapping overhead.

Regarding *partial* big rationals: I am sure having a big numerator and small (1L) denominator is extremely common. Having a small numerator and a large denominator is probably much less common. So maybe a java.math.BigInteger as numerator and a SafeLong as denominator? Probably best to just use SafeLong for both, and maybe deduplicate the denominator in the very common case that it is one.

**Comment by rklaehn** [comment]
How much do we care about backwards compatibility at this point? The class hierarchy I would have in mind would be just Rational, BigRational and LongRational, nothing else. So I would move BigRational and LongRational from BigRationals/LongRationals to the top level. Would that be a problem?

Having programmed OO style for decades (god I'm old!), I would make BigRational and LongRational private[spire]. But it seems that in FP people don't care so much about hiding implementation details, so maybe that is a bad idea.

**Comment by non** [comment]
@rklaehn I am fine breaking binary compatibility to get a better API. I'd prefer to maintain some source compatibility where possible, but obviously I mentioned changing the return types.

I'd say let's focus more on a good design, and worry about compatibility once we hit 1.0.

**Comment by tixxit** [comment]
Yeah - the original design was sort of a compromise between code re-use and not adding extra fields to `LongRational` and `BigRational` classes (eg they should only have) to keep track of companion objects. I think due to bugs and general refactoring, most code has been moved out of RationalLike and we aren't really getting any sort of benefit to having this convoluted design. Even if we did, I'd still opt to make things simpler. So, definitely big :+1: 

As far as binary compatibility or even source, I'm not really that worried. We aren't 1.0 yet, so as long as we bump the minor version, I'm happy.

**Comment by rklaehn** [comment]
Users of rational that don't do anything out of the ordinary should not notice things like RationalLike or BigRational going away. What's your opinion on the visibility? Should LongRational/BigRational be publicly visible? (obviously the constructors that would allow you to violate invariants must *not* be public.

**Comment by tixxit** [comment]
I'm a bit on the fence. On the one hand, it *is* an implementation detail and one I'd rather not expose, since it is conceivable we could replace the implementation with something else in the future. On the other hand, it does let people do things like optimize serialization and whatnot.

I'd lean more towards hiding the implementation though.

**Comment by denisrosset** [comment]
I'd vote to keep an access for the implementations. I'm currently sketching a linear algebra library companion to Spire (http://github.com/denisrosset/qalg), and in the future will mirror the LongRational/BigRational stuff for rational matrices, e.g. use Long arrays for storage if the elements of the rational matrix are small.

Alternatively, we can hide the implementations, but provide methods that enable access to the underlying storage (isNumeratorValidLong, numeratorAsLong, and so on).

**Comment by rklaehn** [comment]
So you just want a way to investigate if a rational is Long/Long or not. I think we can provide that. I find this useful myself, since I am doing something quite similar at work.

**Comment by rklaehn** [comment]
Here is my first draft: https://github.com/rklaehn/spire/blob/feature/rational-refactor/core/src/main/scala/spire/math/Rational.scala

I wonder if we should merge this (this covers point 2. and 5.) before tackling the other points, since I think that switching to SafeLong is a bigger change that is somewhat orthogonal to the inheritance changes?

**Comment by rklaehn** [comment]
By the way: should we add an isOne method? I need it sometimes in my codebase at work, and it seems that other spire types (Natural) also define it.

**Comment by non** [comment]
I totally support adding `isOne` to our number types.

**Comment by rklaehn** [comment]
OK, done.

**Comment by rklaehn** [comment]
Regarding the visibility: Having LongRational and BigRational publicly exposed would make it more difficult to add another implementation in the future, e.g. on platforms such as scala.js that do not have fast longs. So what about hiding the implementation details and just having an additional predicate that returns true if the underlying representation is not using any form of arbitrary precision integer, like *isValidLongLong*?

**Comment by rklaehn** [comment]
Everything except 4. and 6. are done. If somebody wants to work on those, I think it would be best to track this in a different issue.

**Comment by tixxit** [comment]
Is `Rational.nroot` even used? We removed `nroot` from `Rational`, so I think this may just be vestigial code at this point. Can we just delete it?

Here is 4: https://github.com/non/spire/pull/538

**Comment by tixxit** [comment]
6: https://github.com/non/spire/pull/539
