### ISSUE TITLE
Algebra#%'s (modulo) Behavior with Negative Numbers?

### ISSUE THREAD

**Issue by kevinmeredith** [non/spire#461]
How should modulus be handled for negative numbers?

```
scala> Algebraic(-11)
res4: spire.math.Algebraic = -11

scala> Algebraic(5)
res5: spire.math.Algebraic = 5

scala> res4 % res5
res6: spire.math.Algebraic = -1
```

But, per Dr. Pinter's [A Book of Abstract Algebra](store.doverpublications.com/0486474178.html)'s Theorem 2: Division Algorithm:

> If **m** and **n** are integers and **n** is positive, there exist unique integers **q** and **r** such that: `m = nq + r and 0 <= r < n

If I understand that correctly, then, to solve for `-11 % 5`:

>-11 = 5*q + r
>-11 = 5*(-3) + r
> -11 = -15 + r
> therefore, r = 4

please see - https://www.wolframalpha.com/input/?i=-11+mod+5

I admit that I don't fully understand the math behind `Algebraic.scala`, but was curious how modular arithmetic should be calculated.

Thanks.

**Comment by non** [comment]
Hi @kevinmeredith,

The problem here is that there are multiple ways to determine the sign of this operation, and programming languages don't agree. Java (coming from C) uses the sign of the dividend (the first argument) whereas most of us mathematicians would prefer to use the divisor (the second argument). See this wikipedia page for a discussion: https://en.wikipedia.org/wiki/Modulo_operation

It's unfortunate that the custom is to call `%` mod (or modulus), since it corresponds more closely to a remainder. Changing this for our own types will probably cause confusion when the behavior is compared to primitive types (consider `SafeLong` versus `Long`).

My feeling is that we should leave things the way they are. I'm open to suggestions on how to improve this, but unfortunately I feel like Java/Scala tie our hands here.
