### ISSUE TITLE
Request: Access to Snaphot

### ISSUE THREAD

**Issue by hmf** [non/spire#502]
Hello,

Would it be possible to have the current snapshot published in a repository? I see that Travis is being used to check the latest 0.10.2 snapshot and that Cats already has its snapshot available [1]. So I am assuming this is possible. 

If it already is available, my apologies. In that case a pointer on how to get it would be appreciated. 

TIA

1.  https://oss.sonatype.org/content/repositories/snapshots/org/spire-math/

**Comment by non** [comment]
Hi @hmf,

We aren't currently doing this for Spire (AFAIK anyway) so it's just a matter of setting it up. I'm traveling and somewhat oversubscribed, but since master obviously has some important bug fixes I'll try to get to it ASAP.

If you feel like expediting the process feel free to submit a PR porting the relevant `build.sbt` configuration from e.g. Cats to Spire. I think that is the only real barrier to automatically publishing snapshots.

**Comment by hmf** [comment]
Thanks for the feedback. Don't know much about SBT and friends but I look into it. If its easy I will try to do this for Spire.
