### ISSUE TITLE
Every Field should be a VectorSpace

### ISSUE THREAD

**Issue by feijoas** [non/spire#535]
The following code does not work:

``` scala
import spire.algebra._
import spire.syntax._
import spire.implicits._

object MyTest {
  def foo[H](f: H)(implicit ev: VectorSpace[H, Double]) = ???
  foo(1.2)
}

could not find implicit value for parameter ev: spire.algebra.VectorSpace[Double,Double]    
```

however it should as (from [wikipedia](https://en.wikipedia.org/wiki/Examples_of_vector_spaces)):
## Field

The next simplest example (of a vector space) is the field `F` itself. Vector addition is just field addition and scalar multiplication is just field multiplication. Any non-zero element of `F` serves as a basis so `F` is a 1-dimensional vector space over itself.

The field is a rather special vector space; in fact it is the simplest example of a 'algebra over a field algebra over `F`.  Also, `F` has just two Linear subspace: {0} and `F` itself.

**Comment by tixxit** [comment]
It is somewhat intentional to keep these 2 type classes separate, since it can lead to ambiguous implicits in many cases. However, we do have traits for this [0]! They're a bit underserved right now though - it may be worth flushing out a bit.
[0]: https://github.com/non/spire/blob/master/core/shared/src/main/scala/spire/algebra/RingAlgebra.scala#L42

**Comment by denisrosset** [comment]
I ran into problems where an implicit search found a `ZAlgebra` when I was using a Module[M, Int]. I'll try to be more precise and find the problem.

I'd actually like `ZAlgebra`, and 1-d vector spaces to be part of the `optional` subpackage.

**Comment by denisrosset** [comment]
Closing this as part of the clean-up. #674
