### ISSUE TITLE
Publish public Scaladoc for Spire

### ISSUE THREAD

**Issue by non** [non/spire#99]
It would be great to generate and post a Scaladoc for 0.4.0.

**Comment by sarahgerweck** [comment]
I'd like to "me too" to the request that the Spire Scaladoc be published somewhere as part of each release. Right now I end up having to generate the Scaladoc locally whenever I want to work with Spire. The Spire guide isn't bad, but it's can't substitute for Scaladoc.

**Comment by non** [comment]
The people have spoken! :smile: 

I'll look at this again and find a home for the docs.

**Comment by larsrh** [comment]
I will upload the docs for the past couple of releases on docs.typelevel.org this weekend. If I find some time I might even automate it :-)

**Comment by xuwei-k** [comment]
FYI https://github.com/xuwei-k/javadoc-badge

**Comment by larsrh** [comment]
Latest one is up: [http://docs.typelevel.org/api/spire/stable/0.11.0/unidoc/](http://docs.typelevel.org/api/spire/stable/0.11.0/unidoc/)

**Comment by FavioVazquez** [comment]
Hi! Why there's not a link for the Scaladoc in the Readme or anywhere else in the repo? After a lot of searching I found this Issue, and as a new user I think is important to know that the Scaladoc exists and see a direct link to it in the front page, especially due to the fact that this is an amazing library but very specialized. Should be interesting to use @xuwei-k's badge.

**Comment by rklaehn** [comment]
@xuwei-k thanks. This looks useful. I will ask on gitter if we should add it.

@larsrh WDYT: should we just use the badge? I saw that you use it for libisabelle

**Comment by larsrh** [comment]
:+1:

**Comment by rklaehn** [comment]
Most recent scaladoc on maven is now referenced from README.md. So I think we can close this for good!
